// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltimateBrain.Models;

#nullable disable

namespace UltimateBrain.Migrations
{
    [DbContext(typeof(UltimateBrainContext))]
    [Migration("20230506194157_NuevaRelacions")]
    partial class NuevaRelacions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UltimateBrain.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nickName");

                    b.Property<string>("Preguntas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Preguntas");

                    b.Property<int?>("Puntaje")
                        .HasColumnType("int")
                        .HasColumnName("puntaje");

                    b.HasKey("Id")
                        .HasName("PK__particip__3213E83FA6858DC8");

                    b.ToTable("participante", (string)null);
                });

            modelBuilder.Entity("UltimateBrain.Models.Partidum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParticipanteId")
                        .HasColumnType("int");

                    b.Property<int?>("Puntaje")
                        .HasColumnType("int");

                    b.Property<int?>("Tiempo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("UltimateBrain.Models.Preguntum", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("Dificultad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dificultad");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.Property<string>("Respuestas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("respuestas");

                    b.Property<string>("TextoPregunta")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("textoPregunta");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("PK__pregunta__3213E83FAEC31AAD");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("pregunta", (string)null);
                });

            modelBuilder.Entity("UltimateBrain.Models.Respuestum", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("isCorrect");

                    b.Property<int?>("PreguntaId")
                        .HasColumnType("int")
                        .HasColumnName("preguntaId");

                    b.Property<string>("TextoRespuesta")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("textoRespuesta");

                    b.HasKey("Id")
                        .HasName("PK__respuest__3213E83F8D82F32E");

                    b.HasIndex("PreguntaId");

                    b.ToTable("respuesta", (string)null);
                });

            modelBuilder.Entity("UltimateBrain.Models.Partidum", b =>
                {
                    b.HasOne("UltimateBrain.Models.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("UltimateBrain.Models.Preguntum", b =>
                {
                    b.HasOne("UltimateBrain.Models.Participante", "Participante")
                        .WithMany("PreguntasDisponibles")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__pregunta__participante__60A75C0F");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("UltimateBrain.Models.Respuestum", b =>
                {
                    b.HasOne("UltimateBrain.Models.Preguntum", "Pregunta")
                        .WithMany("Respuesta")
                        .HasForeignKey("PreguntaId")
                        .HasConstraintName("FK__respuesta__pregu__60A75C0F");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("UltimateBrain.Models.Participante", b =>
                {
                    b.Navigation("PreguntasDisponibles");
                });

            modelBuilder.Entity("UltimateBrain.Models.Preguntum", b =>
                {
                    b.Navigation("Respuesta");
                });
#pragma warning restore 612, 618
        }
    }
}
